# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vegetablepage.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!

import os
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from cartpagewithtable import Ui_MainWindow2



class Ui_MainWindow1(object):
    file=open('items.txt','w')
    file.truncate(0)
    file.close()
    file1=open('itemnumber.txt','w')
    file1.truncate(0)
    file1.close()
    def cartwindow(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=  Ui_MainWindow2()
        self.ui.setupUi(self.window)
        self.window.show()
    def msgbuttonclick(self,i):
        if i.text()=='&Yes':
            if os.stat("items.txt").st_size==0:
                f=open('items.txt','a')
                f.write("apple")
                f.close()
                g=open('itemnumber.txt','w')
                a=self.comboBox.currentText()
                g.write(a)
                g.close()
            elif os.stat("items.txt").st_size!=0:
                f=open('items.txt','a')
                f.write("\napple")
                f.close()
                g=open('itemnumber.txt','a')
                a=self.comboBox.currentText()
                g.write("\n")
                g.write(a)
                
                g.close()
       
                
                
            
            
    def msgbuttonclick1(self,i):
        if i.text()=='&Yes':
            if os.stat("items.txt").st_size==0:
                    f=open('items.txt','a')
                    f.write("banana")
                    f.close()
                    g=open('itemnumber.txt','w')
                    a=self.comboBox_5.currentText()
                    g.write(a)
                    g.close()
            elif os.stat("items.txt").st_size!=0:
                    f=open('items.txt','a')
                    f.write("\nbanana")
                    f.close()
                    g=open('itemnumber.txt','a')
                    a=self.comboBox_5.currentText()
                    g.write("\n")
                    g.write(a)
                    g.close()
       
            
            
    def msgbuttonclick2(self,i):
         if i.text()=='&Yes':
             if os.stat("items.txt").st_size==0:
                f=open('items.txt','a')
                f.write("orange")
                f.close()
                g=open('itemnumber.txt','w')
                a=self.comboBox_2.currentText()
                g.write(a)
                g.close()
             elif os.stat("items.txt").st_size!=0:
                f=open('items.txt','a')
                f.write("\norange")
                f.close()
                g=open('itemnumber.txt','a')
                a=self.comboBox_2.currentText()
                g.write("\n")
                g.write(a)
                g.close()
       
    def msgbuttonclick3(self,i):
         if i.text()=='&Yes':
             if os.stat("items.txt").st_size==0:
                f=open('items.txt','a')
                f.write("watermelon")
                f.close()
                g=open('itemnumber.txt','w')
                a=self.comboBox_3.currentText()
                g.write(a)
                g.close()
             elif os.stat("items.txt").st_size!=0:
                f=open('items.txt','a')
                f.write("\nwatermelon")
                f.close()
                g=open('itemnumber.txt','a')
                a=self.comboBox_3.currentText()
                g.write("\n")
                g.write(a)
                g.close()
       
    def pushbutton(self):
        msg=QMessageBox()
        msg.setWindowTitle("confirm")
        msg.setText("Do you want add to cart")
        msg.setIcon(QMessageBox.Question)
        msg.setStandardButtons(QMessageBox.Yes|QMessageBox.No)
        
        msg.buttonClicked.connect(self.msgbuttonclick)
        
        x=msg.exec_()
        
        
        
    def pushbutton_4(self):
        msg=QMessageBox()
        msg.setWindowTitle("confirm")
        msg.setText("Do you want add to cart")
        msg.setIcon(QMessageBox.Question)
        msg.setStandardButtons(QMessageBox.Yes|QMessageBox.No)
        
        msg.buttonClicked.connect(self.msgbuttonclick1)
        x=msg.exec_()
       
    def pushbutton_2(self):
        msg=QMessageBox()
        msg.setWindowTitle("confirm")
        msg.setText("Do you want add to cart")
        msg.setIcon(QMessageBox.Question)
        msg.setStandardButtons(QMessageBox.Yes|QMessageBox.No)
        
        msg.buttonClicked.connect(self.msgbuttonclick2)
        x=msg.exec_()
        
    def pushbutton_3(self):
        msg=QMessageBox()
        msg.setWindowTitle("confirm")
        msg.setText("Do you want add to cart")
        msg.setIcon(QMessageBox.Question)
        msg.setStandardButtons(QMessageBox.Yes|QMessageBox.No)
        
        msg.buttonClicked.connect(self.msgbuttonclick3)
        x=msg.exec_()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1208, 776)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.centralwidget.setPalette(palette)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 120, 241, 291))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("12th computer project/apple.PNG"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(320, 120, 241, 291))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("12th computer project/banana.PNG"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(610, 120, 241, 291))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("12th computer project/orange.PNG"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(910, 120, 231, 291))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("12th computer project/watermelon.PNG"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(130, 420, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(99, 420, 31, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setItemText(9, "")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(730, 420, 81, 21))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(1020, 420, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(420, 420, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(990, 0, 181, 71))
        self.pushButton_6.setObjectName("pushButton_6")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(170, 20, 331, 31))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(500, 20, 81, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(80, 420, 21, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(370, 420, 21, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(680, 420, 21, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(970, 420, 21, 16))
        self.label_8.setObjectName("label_8")
        self.comboBox_5 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_5.setGeometry(QtCore.QRect(389, 420, 31, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.setItemText(9, "")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(699, 420, 31, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.setItemText(9, "")
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(989, 420, 31, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.setItemText(9, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1208, 21))
        self.menubar.setObjectName("menubar")
        self.menuCATEGORIES = QtWidgets.QMenu(self.menubar)
        self.menuCATEGORIES.setObjectName("menuCATEGORIES")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionvegetables = QtWidgets.QAction(MainWindow)
        self.actionvegetables.setObjectName("actionvegetables")
        self.actionfruits = QtWidgets.QAction(MainWindow)
        self.actionfruits.setObjectName("actionfruits")
        self.actionbeverages = QtWidgets.QAction(MainWindow)
        self.actionbeverages.setObjectName("actionbeverages")
        self.actionbakery_and_diary = QtWidgets.QAction(MainWindow)
        self.actionbakery_and_diary.setObjectName("actionbakery_and_diary")
        self.actionfoodgrains = QtWidgets.QAction(MainWindow)
        self.actionfoodgrains.setObjectName("actionfoodgrains")
        self.menuCATEGORIES.addAction(self.actionvegetables)
        self.menuCATEGORIES.addAction(self.actionfruits)
        self.menuCATEGORIES.addAction(self.actionbeverages)
        self.menuCATEGORIES.addAction(self.actionbakery_and_diary)
        self.menuCATEGORIES.addAction(self.actionfoodgrains)
        self.menubar.addAction(self.menuCATEGORIES.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "add to cart"))
        self.pushButton.clicked.connect(self.pushbutton)
        self.comboBox.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox.setItemText(8, _translate("MainWindow", "9"))
        self.pushButton_2.setText(_translate("MainWindow", "add to cart"))
        self.pushButton_2.clicked.connect(self.pushbutton_2)
        self.pushButton_3.setText(_translate("MainWindow", "add to cart"))
        self.pushButton_3.clicked.connect(self.pushbutton_3)
        self.pushButton_4.setText(_translate("MainWindow", "add to cart"))
        self.pushButton_4.clicked.connect(self.pushbutton_4)
        self.pushButton_6.setText(_translate("MainWindow", "MY ITEMS"))
        self.pushButton_6.clicked.connect(self.cartwindow)
        self.pushButton_5.setText(_translate("MainWindow", "SEARCH"))
        self.label_5.setText(_translate("MainWindow", "Qty"))
        self.label_6.setText(_translate("MainWindow", "Qty"))
        self.label_7.setText(_translate("MainWindow", "Qty"))
        self.label_8.setText(_translate("MainWindow", "Qty"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_5.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_5.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_5.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_5.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_5.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_3.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_3.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_3.setItemText(8, _translate("MainWindow", "9"))
        self.menuCATEGORIES.setTitle(_translate("MainWindow", "CATEGORIES"))
        self.actionvegetables.setText(_translate("MainWindow", "vegetables"))
        self.actionfruits.setText(_translate("MainWindow", "fruits"))
        self.actionbeverages.setText(_translate("MainWindow", "beverages"))
        self.actionbakery_and_diary.setText(_translate("MainWindow", "bakery and diary"))
        self.actionfoodgrains.setText(_translate("MainWindow", "foodgrains"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow1()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
